// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CleanArchitecture.Domain.Entities
{
    public partial class Genres
    {
        public Genres()
        {
            Albums = new HashSet<Albums>();
        }

        public int GenreId { get; set; }
        public string Genre { get; set; }

        public virtual ICollection<Albums> Albums { get; set; }
    }
}