// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CleanArchitecture.API.DTOs
{
    public partial class ArtistDTO
    {
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
        public DateTime? ActiveFrom { get; set; }
    }
}